# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faab0025e818edb4e825de694523ba45c231c369fc97676a8624167fed3ea9d691ef934ee2ecc8ee0a1c894f221ce378e090c57723174614c070633d509f9246

test:
  secret_key_base: 0f5bcadbd2fab33b655a8504b813b6733382cca51c782d00c73d0703e88853f94c7ee9886d354417e6fd43d1e093356abd8f40a095567583dd1d543edc95e6a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: e345e47cc7642fd049a973b82330a455d0d8aa110c7cc6ac626bf6654a43da5e32e75dd91bf830b385d9d590b56d70575622bded3d13fb04b4e321fe84377dcf

